
=pod

=head1 NAME

gfsmcompile - Compile text format gfsm files to binary



=head1 SYNOPSIS

gfsmcompile [OPTIONS] TXTFILE

 Arguments:
    TXTFILE  Input text file

 Options
    -h        --help             Print help and exit.
    -V        --version          Print version and exit.
    -cFILE    --rcfile=FILE      Read an alternate configuration file.
    -a        --acceptor         Compile as acceptor (default=transducer)
    -iLABELS  --ilabels=LABELS   Specify input (lower) labels file.
    -oLABELS  --olabels=LABELS   Specify output (upper) labels file.
    -SLABELS  --slabels=LABELS   Specify state labels file.
    -sSRTYPE  --semiring=SRTYPE  Specify semiring type.
    -zLEVEL   --compress=LEVEL   Specify compression level of output file.
    -FFILE    --output=FILE      Specifiy output file (default=stdout).

=cut

###############################################################
# Description
###############################################################
=pod

=head1 DESCRIPTION

Compile text format gfsm files to binary



=cut

###############################################################
# Arguments
###############################################################
=pod

=head1 ARGUMENTS

=over 4

=item C<TXTFILE>

Input text file


If unspecified, standard input will be read


=back



=cut


###############################################################
# Options
###############################################################
=pod

=head1 OPTIONS

=over 4

=item C<--help> , C<-h>

Print help and exit.

Default: '0'




=item C<--version> , C<-V>

Print version and exit.

Default: '0'




=item C<--rcfile=FILE> , C<-cFILE>

Read an alternate configuration file.

Default: 'NULL'

See also: L<CONFIGURATION FILES>.




=item C<--acceptor> , C<-a>

Compile as acceptor (default=transducer)

Default: '0'




=item C<--ilabels=LABELS> , C<-iLABELS>

Specify input (lower) labels file.

Default: 'NULL'




=item C<--olabels=LABELS> , C<-oLABELS>

Specify output (upper) labels file.

Default: 'NULL'




=item C<--slabels=LABELS> , C<-SLABELS>

Specify state labels file.

Default: 'NULL'




=item C<--semiring=SRTYPE> , C<-sSRTYPE>

Specify semiring type.

Default: 'tropical'


Specify one of the following:

 boolean
 log
 plog
 real
 trivial
 tropical






=item C<--compress=LEVEL> , C<-zLEVEL>

Specify compression level of output file.

Default: '-1'


Specify zlib compression level of output file. -1 (default) indicates
the default compression level, 0 (zero) indicates no zlib compression at all,
and 9 indicates the best possible compression.





=item C<--output=FILE> , C<-FFILE>

Specifiy output file (default=stdout).

Default: '-'




=back




=cut

###############################################################
# configuration files
###############################################################
=pod

=head1 CONFIGURATION FILES

Configuration files are expected to contain lines of the form:

    LONG_OPTION_NAME    OPTION_VALUE

where LONG_OPTION_NAME is the long name of some option,
without the leading '--', and OPTION_VALUE is the value for
that option, if any.  Fields are whitespace-separated.
Blank lines and comments (lines beginning with '#')
are ignored.

No configuration files are read by default.

=cut



###############################################################
# Addenda
###############################################################
=pod

=head1 ADDENDA



=head2 About this Document

Documentation file auto-generated by optgen.perl version 0.05.
Translation was initiated on
Mon Oct 22 15:35:43 CEST 2007
as:

   /usr/bin/optgen.perl -l --nocfile --nohfile -F gfsmcompile gfsmcompile.gog

=cut


###############################################################
# Bugs
###############################################################
=pod

=head1 BUGS AND LIMITATIONS



None known.



=cut

###############################################################
# Footer
###############################################################
=pod

=head1 ACKNOWLEDGEMENTS

Perl by Larry Wall.

Getopt::Gen by Bryan Jurish.

=head1 AUTHOR

Bryan Jurish E<lt>moocow@ling.uni-potsdam.deE<gt>

=head1 SEE ALSO


L<gfsmutils>


=cut



