


=pod

=head1 NAME

gfsmarcsort - Sort arcs of a finite state machine



=head1 SYNOPSIS

gfsmarcsort [OPTIONS] BINFILE

 Arguments:
    BINFILE  Stored binary gfsm file

 Options
    -h       --help            Print help and exit.
    -V       --version         Print version and exit.
    -l       --lower           Sort by (lower,upper,target) [default].
    -u       --upper           Sort by (upper,lower,target).
    -w       --weight          Sort by weight (ascending).
    -i                         Alias for '--lower'
    -o                         Alias for '--upper'
    -C       --cost            Alias for '--weight'
    -mMODE   --mode=MODE       Sort by explicit mode string (overrides -l, -u, etc.)
    -U       --unique          After sorting, collect weights on otherwise identical arcs
    -zLEVEL  --compress=LEVEL  Specify compression level of output file.
    -FFILE   --output=FILE     Specifiy output file (default=stdout).

=cut

###############################################################
# Description
###############################################################
=pod

=head1 DESCRIPTION

Sort arcs of a finite state machine



=cut

###############################################################
# Arguments
###############################################################
=pod

=head1 ARGUMENTS

=over 4

=item C<BINFILE>

Stored binary gfsm file


If unspecified, standard input will be read


=back



=cut


###############################################################
# Options
###############################################################
=pod

=head1 OPTIONS

=over 4

=item C<--help> , C<-h>

Print help and exit.

Default: '0'




=item C<--version> , C<-V>

Print version and exit.

Default: '0'




=item C<--lower> , C<-l>

Sort by (lower,upper,target) [default].

Default: '0'




=item C<--upper> , C<-u>

Sort by (upper,lower,target).

Default: '0'




=item C<--weight> , C<-w>

Sort by weight (ascending).

Default: '0'




=item C<-i>

Alias for '--lower'

Default: '0'




=item C<-o>

Alias for '--upper'

Default: '0'




=item C<--cost> , C<-C>

Alias for '--weight'

Default: '0'




=item C<--mode=MODE> , C<-mMODE>

Sort by explicit mode string (overrides -l, -u, etc.)

Default: ''


Sort by a mode string over the characters "luwstLUWST_", as accepted
by gfsm_acmask_from_chars().  Each character in the string represents
a single elementary arc field comparison, and the comparison with the
highest priority should occur leftmost in the string.  Correspondence
between characters in MODE and arc comparisons is:

  CHAR : COMPARISON
     l : sort by lower labels in ascending order
     u : sort by upper labels in ascending order
     w : sort by arc weight in semiring-ascending order
     s : sort by source state in ascending order (useless here)
     t : sort by target state in ascending order

     L : sort by lower labels in descending order
     U : sort by upper labels in descending order
     W : sort by arc weight in semiring-descending order
     S : sort by source state in descending order (useless here)
     T : sort by target state in descending order

     _ : no comparison at the corresponding priority level
     x : user-specified comparison (useless here)






=item C<--unique> , C<-U>

After sorting, collect weights on otherwise identical arcs

Default: '0'


This is exactly what a subsequent call of L<gfsmarcuniq(1)|gfsmarcuniq> does.





=item C<--compress=LEVEL> , C<-zLEVEL>

Specify compression level of output file.

Default: '-1'


Specify zlib compression level of output file. -1 (default) indicates
the default compression level, 0 (zero) indicates no zlib compression at all,
and 9 indicates the best possible compression.





=item C<--output=FILE> , C<-FFILE>

Specifiy output file (default=stdout).

Default: '-'




=back




=cut

###############################################################
# configuration files
###############################################################
=pod



=cut


###############################################################
# Addenda
###############################################################
=pod

=head1 ADDENDA



=head2 About this Document

Documentation file auto-generated by optgen.perl version 0.07
using Getopt::Gen version 0.14.
Translation was initiated
as:

   optgen.perl -l --no-handle-rcfile --nocfile --nohfile --notimestamp -F gfsmarcsort gfsmarcsort.gog

=cut


###############################################################
# Bugs
###############################################################
=pod

=head1 BUGS AND LIMITATIONS



None known.



=cut

###############################################################
# Footer
###############################################################
=pod

=head1 ACKNOWLEDGEMENTS

Perl by Larry Wall.

Getopt::Gen by Bryan Jurish.

=head1 AUTHOR

Bryan Jurish E<lt>moocow.bovine@gmail.comE<gt>

=head1 SEE ALSO


L<gfsmutils>


=cut


