
=pod

=head1 NAME

gfsmutils - finite state machine command-line utilities

=head1 PROGRAMS

The following is a list of the programs
and user documentation contained in the gfsm package.
See the individual manpages for details.

=head2 gfsmarcsort

Sort arcs of a finite state machine

See L<gfsmarcsort> for details.


=head2 gfsmarith

Perform an elementary arithmetic operation on automaton weights

See L<gfsmarith> for details.


=head2 gfsmclosure

Compute Kleene closure of a finite state machine

See L<gfsmclosure> for details.


=head2 gfsmcompile

Compile text format gfsm files to binary

See L<gfsmcompile> for details.


=head2 gfsmcomplement

Compute complement of finite state acceptors

See L<gfsmcomplement> for details.


=head2 gfsmcompose

Compute composition of finite-state machines

See L<gfsmcompose> for details.


=head2 gfsmcompre

Compile an automaton from a regular expression

See L<gfsmcompre> for details.


=head2 gfsmconcat

Concatenate finite state machines

See L<gfsmconcat> for details.


=head2 gfsmconnect

Remove non-coaccessible states from finite state machines

See L<gfsmconnect> for details.


=head2 gfsmconvert

Convert binary format gfsm files

See L<gfsmconvert> for details.


=head2 gfsmdeterminize

Determinize a finite state machine

See L<gfsmdeterminize> for details.


=head2 gfsmdifference

Compute difference of epsilon-free finite state acceptors

See L<gfsmdifference> for details.


=head2 gfsmdraw

Generate graph specifications from binary gfsm files

See L<gfsmdraw> for details.


=head2 gfsmheader

Show header information from stored gfsm files

See L<gfsmheader> for details.


=head2 gfsminfo

Show basic information about stored gfsm files

See L<gfsminfo> for details.


=head2 gfsmintersect

Compute intersection of finite state acceptors

See L<gfsmintersect> for details.


=head2 gfsminvert

Invert input/output tapes of finite state machines

See L<gfsminvert> for details.


=head2 gfsmlabels

Map input text characters to gfsm labels

See L<gfsmlabels> for details.


=head2 gfsmlookup

Apply a transducer to a linear label sequence

See L<gfsmlookup> for details.


=head2 gfsmoptional

Make a an automaton optional

See L<gfsmoptional> for details.


=head2 gfsmprint

Convert binary format gfsm files to text

See L<gfsmprint> for details.


=head2 gfsmproduct

Compute Cartesian product of finite state acceptors

See L<gfsmproduct> for details.


=head2 gfsmproject

Project one side of finite state machines

See L<gfsmproject> for details.


=head2 gfsmrenumber

Renumber states in finite state machines

See L<gfsmrenumber> for details.


=head2 gfsmreplace

Replace some automaton arcs with a whole automaton

See L<gfsmreplace> for details.


=head2 gfsmreverse

Reverse a finite state machine

See L<gfsmreverse> for details.


=head2 gfsmrmepsilon

Remove epsilon arcs from finite state machines

See L<gfsmrmepsilon> for details.


=head2 gfsmsigma

Create a single-state alphabet acceptor

See L<gfsmsigma> for details.


=head2 gfsmstrings

Serialize binary acyclic gfsm files to lists of strings

See L<gfsmstrings> for details.


=head2 gfsmunion

Compute union of finite state machines

See L<gfsmunion> for details.


=head2 gfsmviterbi

EXPERIMENTAL: Compute Viterbi trellis for a linear label sequence in a transducer

See L<gfsmviterbi> for details.




=cut

###############################################################
# Description
###############################################################
=pod

=head1 DESCRIPTION

The gfsmutils package provides a suite of command-line tools
for manipulation of finite state machines (FSMs) using
the libgfsm library.

=cut

###############################################################
# Addenda
###############################################################
=pod

=head1 ADDENDA

=head2 About this Document

Documentation file auto-generated by optgen.perl version 0.06.
Translation was initiated
as:

   --nocfile --nohfile --nopod --no-handle-help --no-handle-version --no-handle-rcfile --no-handle-error --notimestamp --template=gfsmutils.skel -

=cut


###############################################################
# Footer
###############################################################
#=pod
#
#=head1 ACKNOWLEDGEMENTS
#
##[ @ join('',`cat acknowledge.pod`); @ ]

=head1 SEE ALSO

=over 4

=item gfsm Project Page:

L<http://www.ling.uni-potsdam.de/~moocow/projects/gfsm>

=item gfsm Utility Manuals:

gfsmarcsort(1), gfsmarith(1), gfsmclosure(1), gfsmcompile(1), gfsmcomplement(1), gfsmcompose(1), gfsmcompre(1), gfsmconcat(1), gfsmconnect(1), gfsmconvert(1), gfsmdeterminize(1), gfsmdifference(1), gfsmdraw(1), gfsmheader(1), gfsminfo(1), gfsmintersect(1), gfsminvert(1), gfsmlabels(1), gfsmlookup(1), gfsmoptional(1), gfsmprint(1), gfsmproduct(1), gfsmproject(1), gfsmrenumber(1), gfsmreplace(1), gfsmreverse(1), gfsmrmepsilon(1), gfsmsigma(1), gfsmstrings(1), gfsmunion(1), gfsmviterbi(1)

=item Other

fsm(1), fsm(5)

=back

=head1 AUTHOR

Bryan Jurish E<lt>moocow@ling.uni-potsdam.deE<gt>

=cut
