


=pod

=head1 NAME

gfsmlabels - Map input text characters to gfsm labels



=head1 SYNOPSIS

gfsmlabels [OPTIONS] TXTFILE

 Arguments:
    TXTFILE  Input text file

 Options
    -h        --help           Print help and exit.
    -V        --version        Print version and exit.
    -lLABELS  --labels=LABELS  Specify input alphabet (labels) file.
    -a        --att-mode       Parse string(s) in AT&T-compatible mode.
    -m        --map-mode       Output original strings in addition to label vectors.
    -q        --quiet          Suppress warnings about undefined symbols.
    -u        --utf8           Assume UTF-8 encoded alphabet and input
    -oFILE    --output=FILE    Specifiy output file (default=stdout).

=cut

###############################################################
# Description
###############################################################
=pod

=head1 DESCRIPTION

Map input text characters to gfsm labels



=cut

###############################################################
# Arguments
###############################################################

=pod

=head1 ARGUMENTS

=over 4

=item C<TXTFILE>

Input text file


If unspecified, standard input will be read.


=back



=cut



###############################################################
# Options
###############################################################

=pod

=head1 OPTIONS

=over 4

=item C<--help> , C<-h>

Print help and exit.

Default: '0'




=item C<--version> , C<-V>

Print version and exit.

Default: '0'




=item C<--labels=LABELS> , C<-lLABELS>

Specify input alphabet (labels) file.

Default: 'NULL'




=item C<--att-mode> , C<-a>

Parse string(s) in AT&T-compatible mode.

Default: '0'




=item C<--map-mode> , C<-m>

Output original strings in addition to label vectors.

Default: '0'




=item C<--quiet> , C<-q>

Suppress warnings about undefined symbols.

Default: '0'




=item C<--utf8> , C<-u>

Assume UTF-8 encoded alphabet and input

Default: '0'




=item C<--output=FILE> , C<-oFILE>

Specifiy output file (default=stdout).

Default: '-'




=back




=cut



###############################################################
# configuration files
###############################################################



###############################################################
# Addenda
###############################################################

=pod

=head1 ADDENDA



=head2 About this Document

Documentation file auto-generated by optgen.perl version 0.07
using Getopt::Gen version 0.14.
Translation was initiated
as:

   optgen.perl -l --no-handle-rcfile --nocfile --nohfile --notimestamp -F gfsmlabels gfsmlabels.gog

=cut


###############################################################
# Bugs
###############################################################
=pod

=head1 BUGS AND LIMITATIONS



None known.



=cut

###############################################################
# Footer
###############################################################
=pod

=head1 ACKNOWLEDGEMENTS

Perl by Larry Wall.

Getopt::Gen by Bryan Jurish.

=head1 AUTHOR

Bryan Jurish E<lt>moocow.bovine@gmail.comE<gt>

=head1 SEE ALSO


L<gfsmutils>


=cut


